# Generated by Django 5.0.7 on 2024-08-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kahoot_app', '0002_question_question_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_number',
        ),
    ]
